### ISSUE TITLE
Project roadmap for version 2

### ISSUE THREAD

**Issue by drublic** [use-init/init#123]
In general the project should maintain it's position as a starting point for website projects and web apps by providing a great default of tools and workflows for developers. These devs seem to be mostly @anselmh and myself.
Please let us know of any additions you think would be useful.

So here are the plans we have for version 2.
### Remove Bower in favor of npm
- [x] As it seems Bower will be deprecated in the foreseeable future. [There hasn't been a lot of development in Bower](https://github.com/bower/bower/graphs/contributors?from=2014-06-13&to=2014-11-01&type=c) over the last 12 months, [npm is trying to provide a better package management for the front end](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) in the future, a lot of projects shift to or add npm for publishing their releases (as for instance AngularJS) or use npm for their deps (HTML5 Boilerplate). Apart from that we currently use two package management tools which basically do similar stuff. npm seems to be a future-prove solution. (PR #125)
### Remove Sass in favor of Pleeease
- [x] Remove Sass in favor of [Pleeease](http://pleeease.io/) as a post-processor: Even though development with Sass got a lot faster with the shift to libsass it is still slow. Sass adds features to CSS which are not thought to be part of the descriptive language which CSS is. Thus they add more complexity to your project and the code you write. Sass has some awesome features as for example variables, nesting and color-functions which are currently not supported in CSS. But these features are on their way to land in browsers with standardized implementations. Pleeease enables us to use a couple of these features today and makes it easier to use CSS without thinking about vendor prefixes or problematic import rules. This also makes the sass-mixins package not necessary anymore and lets us switch to the default CSS implementation of normalize.css. (PR #124)
### Drop IE8 support
- [x] Dropping IE8: Most of our projects do not require a lot of IE8 support anymore and numbers of IE8 users in general are dropping. We believe we can use jQuery v2 now safely but we also know people's concerns about dropping IE8 support completely. You can always update the version of packages with npm very easy.
### ~~Static Page Generator~~

Note: The static site generator will be available as a plugin in v2.
- Better static page generator: We want to add a some kind of post/blog engine which has overview pages and better integration of detail pages for people who want to manage their blog with INIT.
  - We need a proper URL structure for it and would need to let the user configure if a page is a folder or not (means it creates a `about/index.html` or `about.html`)
  - We need to get rid of the pages.json at least for articles and similar types of pages as it's not practical to add these manually to the JSON each time you add a new post.
  - Extend pages functionality with meta-information like a _publishing date, author, state (draft, published, hiddencopy)_
  - Use a more automated process to generate pages and use provided information instead of a separate config file (pages.json).
### Cleanup
- [x] Rethink project structure: In order to make it more clear how we can work better there will be an improved file structure which is partly implemented in the branch v2.0 already.
- [ ] Clean structure to integrate plugins (npm modules, maybe a copy via post install hook), detailed implementation to be discussed.
- [x] Analytics in separate JS file with implementation for sending events
- [ ] Improved documentation
### More

Also there are a couple of ideas which we haven't really found a final decision yet:
- [x] RequireJS: replace with ES6 module definition and use the [ES6 transpiler](http://esnext.github.io/es6-module-transpiler/) for ES5 compatibility.
- [x] ~~RequireJS replacement: Use browserify for use with CommonJS modules.~~
- [x] ~~Optional Helpers for JS and CSS~~

**Comment by anselmh** [comment]
I’d go with [`grunt-generator`](https://www.npmjs.com/package/grunt-generator) for the static site builder. It has all the options at least I want to have and it even let me decide how to write the templates and options. What do you think @drublic?
I’ll see if I get an example branch running with it quickly.

**Comment by drublic** [comment]
The plugin looks quite nice. +1 on adding it.

**Comment by anselmh** [comment]
[WIP] https://github.com/use-init/init-static-site-generator
