### ISSUE TITLE
Add better docs

### ISSUE THREAD

**Issue by drublic** [use-init/init#40]
This is a multi-task issue. Here we can collect what should be documented for the 1.0.0 release.
It replaces #29 and #32.
- [x] **General purpose** of the project.
- [x] **Build process:** We should write a documentation how the build and deployment process works / can work. Currently some users have problems what you need to do before using grunt deploy to achieve the proper results. This issue depends on major improvements in the code itself (automate versioned filenames etc.) (#32). _Blocked by #5_.
- [x] Usage of **Livereload**, **svgmin** in grunt-contrib-watch task (#29).
- [x] How to write **modules with Sass** (#41).
- [x] How to write **modules with RequireJS** in JavaScript.
- [x] How grunt, bower and requireJS work.
- [ ] How to update a project / its components built upon init.  
  ~~\- [ ] Include this all on a website (#43).~~

Please feel free to share what needs documentation in the comments. I will then update the list above.
